2022-02-22 23:35:32,331 INFO    MainThread:40520 [wandb_setup.py:_flush():71] setting env: {}
2022-02-22 23:35:32,331 INFO    MainThread:40520 [wandb_setup.py:_flush():71] setting login settings: {}
2022-02-22 23:35:32,332 INFO    MainThread:40520 [wandb_init.py:_log_setup():371] Logging user logs to E:\learn\github_project\yolov5-face\wandb\run-20220222_233532-akuzynsx\logs\debug.log
2022-02-22 23:35:32,332 INFO    MainThread:40520 [wandb_init.py:_log_setup():372] Logging internal logs to E:\learn\github_project\yolov5-face\wandb\run-20220222_233532-akuzynsx\logs\debug-internal.log
2022-02-22 23:35:32,332 INFO    MainThread:40520 [wandb_init.py:init():404] calling init triggers
2022-02-22 23:35:32,332 INFO    MainThread:40520 [wandb_init.py:init():409] wandb.init called with sweep_config: {}
config: {'weights': 'weights/yolov5s.pt', 'cfg': 'models/yolov5s.yaml', 'data': 'data/widerface.yaml', 'hyp': {'lr0': 0.01, 'lrf': 0.2, 'momentum': 0.937, 'weight_decay': 0.0005, 'warmup_epochs': 3.0, 'warmup_momentum': 0.8, 'warmup_bias_lr': 0.1, 'box': 0.05, 'cls': 0.5, 'landmark': 0.005, 'cls_pw': 1.0, 'obj': 1.0, 'obj_pw': 1.0, 'iou_t': 0.2, 'anchor_t': 4.0, 'fl_gamma': 0.0, 'hsv_h': 0.015, 'hsv_s': 0.7, 'hsv_v': 0.4, 'degrees': 0.0, 'translate': 0.1, 'scale': 0.5, 'shear': 0.5, 'perspective': 0.0, 'flipud': 0.0, 'fliplr': 0.5, 'mosaic': 0.5, 'mixup': 0.0}, 'epochs': 250, 'batch_size': 16, 'img_size': [800, 800], 'rect': False, 'resume': False, 'nosave': False, 'notest': False, 'noautoanchor': False, 'evolve': False, 'bucket': '', 'cache_images': False, 'image_weights': False, 'device': '', 'multi_scale': False, 'single_cls': False, 'adam': False, 'sync_bn': False, 'local_rank': -1, 'log_imgs': 16, 'log_artifacts': False, 'workers': 4, 'project': 'runs/train', 'name': 'exp', 'exist_ok': False, 'total_batch_size': 16, 'world_size': 1, 'global_rank': -1, 'save_dir': 'runs\\train\\exp14'}
2022-02-22 23:35:32,332 INFO    MainThread:40520 [wandb_init.py:init():460] starting backend
2022-02-22 23:35:32,333 INFO    MainThread:40520 [backend.py:_multiprocessing_setup():99] multiprocessing start_methods=spawn, using: spawn
2022-02-22 23:35:32,338 INFO    MainThread:40520 [backend.py:ensure_launched():216] starting backend process...
2022-02-22 23:35:32,440 INFO    MainThread:40520 [backend.py:ensure_launched():221] started backend process with pid: 28112
2022-02-22 23:35:32,441 INFO    MainThread:40520 [wandb_init.py:init():469] backend started and connected
2022-02-22 23:35:32,442 INFO    MainThread:40520 [wandb_init.py:init():533] updated telemetry
2022-02-22 23:35:32,446 INFO    MainThread:40520 [wandb_init.py:init():563] communicating current version
2022-02-22 23:35:34,004 INFO    MainThread:40520 [wandb_init.py:init():568] got version response 
2022-02-22 23:35:34,004 INFO    MainThread:40520 [wandb_init.py:init():578] communicating run to backend with 30 second timeout
2022-02-22 23:36:04,005 INFO    MainThread:40520 [interface_shared.py:_communicate_run():313] couldn't get run from backend
2022-02-22 23:36:04,005 ERROR   MainThread:40520 [wandb_init.py:init():583] backend process timed out
2022-02-22 23:36:04,005 ERROR   MainThread:40520 [wandb_init.py:init():592] encountered error: Error communicating with wandb process
try: wandb.init(settings=wandb.Settings(start_method='fork'))
or:  wandb.init(settings=wandb.Settings(start_method='thread'))
For more info see: https://docs.wandb.ai/library/init#init-start-error
